/**
 * Global Constants for YoRHa-HexFlow Application
 */

export const OP_CODES = {
    HEX_RAW: 'HEX_RAW',
    INT_UNSIGNED: 'INT_UNSIGNED',
    INT_SIGNED: 'INT_SIGNED',
    FLOAT_IEEE: 'FLOAT_IEEE',
    SCALED_DECIMAL: 'SCALED_DECIMAL',
    BCD_CODE: 'BCD_CODE',
    BITFIELD: 'BITFIELD',
    MAPPING: 'MAPPING',
    ARRAY_GROUP: 'ARRAY_GROUP',
    LENGTH_CALC: 'LENGTH_CALC',
    CHECKSUM_CRC: 'CHECKSUM_CRC',
    TIME_ACCUMULATOR: 'TIME_ACCUMULATOR',
    AUTO_COUNTER: 'AUTO_COUNTER'
};

export const CATEGORIES = {
    BASE: 'BASE',
    NUMERIC: 'NUMERIC',
    ENCODING: 'ENCODING',
    DYNAMIC: 'DYNAMIC',
    LOGIC: 'LOGIC',
    STRUCT: 'STRUCT'
};

export const OP_PRIORITY = [
    OP_CODES.HEX_RAW,
    OP_CODES.INT_UNSIGNED,
    OP_CODES.INT_SIGNED,
    OP_CODES.FLOAT_IEEE,
    OP_CODES.SCALED_DECIMAL,
    OP_CODES.BCD_CODE,
    OP_CODES.BITFIELD,
    OP_CODES.TIME_ACCUMULATOR,
    OP_CODES.AUTO_COUNTER,
    OP_CODES.MAPPING,
    OP_CODES.ARRAY_GROUP,
    OP_CODES.LENGTH_CALC,
    OP_CODES.CHECKSUM_CRC
];

export const CATEGORY_ORDER = [
    CATEGORIES.BASE,
    CATEGORIES.NUMERIC,
    CATEGORIES.ENCODING,
    CATEGORIES.DYNAMIC,
    CATEGORIES.LOGIC,
    CATEGORIES.STRUCT
];
